# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage animated_java:temp args.uuid set from storage animated_java:data "$(id)".uuid
scoreboard players set #success aj.i 0
function animated_java:global/data_manager/zzz/1 with storage animated_java:temp args