# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store success score #success aj.i if score $(uuid) aj.id matches 1..
$execute if score #success aj.i matches 0 run data remove storage animated_java:data "$(id)"