modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "LicenseRef-Custom"
showAsResourcePack = false
issueTrackerURL = "https://discord.kohara.xyz/"

[[mods]]
	modId = "stellarity" 
	version = "3.0.3"
	displayName = "Stellarity"
	displayURL = "https://modrinth.com/datapack/stellarity"
	description = '''
	Extreme rehaul and expansion of The End!
	'We have End Update at home.'
	'''
	logoFile = "pack.png"
	logoBlur = false
	updateJSONURL = "https://api.modrinth.com/updates/bZgeDzN8/forge_updates.json"
	credits="brokenemp (Artist), Dat1Mexican (RP Bedrock Port), Bush_King (Builder), Opliz (Builder)"
	authors = "kohara"

[[dependencies.stellarity]]
	modId="forge"
	mandatory=false
	versionRange="[51,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.stellarity]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21,1.21.1]"
	ordering="NONE"
	side="BOTH"
