modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "LicenseRef-Custom"
showAsResourcePack = false
issueTrackerURL = "https://discord.com/invite/5u3TTVmkSq"

[[mods]]
modId = "stellarity"
version = "5.4.1"
displayName = "Stellarity"
displayURL = "https://modrinth.com/datapack/stellarity"
description = '''
	Extreme rehaul and expansion of The End!
	'We have End Update at home.'
	'''
logoFile = "pack.png"
logoBlur = false
updateJSONURL = "https://api.modrinth.com/updates/bZgeDzN8/forge_updates.json"
credits = "BananaKingXO (Developer), brokenemp (Artist), Dat1Mexican (RP Bedrock Port), Bush_King (Builder), Opliz (Builder), Coder2195 (Builder), Alligator_Gamer (Artist)"
authors = "kohara"

[[dependencies.stellarity]]
modId = "forge"
mandatory = false
versionRange = "[51,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.stellarity]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1,26.1]"
ordering = "NONE"
side = "BOTH"
