modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "LicenseRef-Custom"
showAsResourcePack = false
issueTrackerURL = "http://discord.prismaticshards.xyz"

[[mods]]
modId = "stellarity"
version = "6.0.0"
displayName = "Stellarity"
displayURL = "https://modrinth.com/datapack/stellarity"
description = '''
	Extreme rehaul and expansion of The End!
	'We have End Update at home.'
	'''
logoFile = "pack.png"
logoBlur = false
updateJSONURL = "https://api.modrinth.com/updates/bZgeDzN8/forge_updates.json"
credits = "BananaKingXO (Head Developer), Coder2195 (Developer), Alligator_Gamer (Artist), WildPlacedPixel (Artist), Midas (Artist), brokenemp (Artist), Dat1Mexican (RP Bedrock Port), Bush_King (Builder), Opliz (Builder)"
authors = "kohara"

[[dependencies.stellarity]]
modId = "neoforge"
mandatory = false
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.stellarity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.11,26.3]"
ordering = "NONE"
side = "BOTH"
