# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless score @s aj.id matches -2147483648..2147483647 run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (stellarity:util/animated_java/pixie)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Entity with ID Score',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'stellarity:util/animated_java/pixie/as_root'}]}},' must be executed as an entity with a ',{text:aj.id,color:yellow},' score.','\n']
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
$data modify storage animated_java:temp args.command set value '$(command)'
data modify storage animated_java:temp args.root_uuid set from storage animated_java:temp entry.data.root_uuid
function stellarity:util/animated_java/pixie/as_root_entity with storage animated_java:temp args