# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage stellarity:util/animated_java/pixie rig_hash set value '1fc553b74340010324e2c0c619ba8ce4fc37721ddeeadfcf9e0720d40b61f9bf'
scoreboard objectives add aj.idle_pixie.frame dummy
scoreboard objectives add aj.flying_pixie.frame dummy