# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage stellarity:util/animated_java/pixie rig_hash set value '6b6df6249671aaa2842c4c7c2843091cbc6dfbe0ee271c6bf41cc8fe9037e83e'
scoreboard objectives add aj.idle_pixie.frame dummy
scoreboard objectives add aj.flying_pixie.frame dummy