# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '379548520414704f61dda363263eaf599f96402bbfbbb1ba2ac607faaf5d4c8a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack