# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.8755f,0f,0f,-1f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9962f,0.0872f,0.8755f,0f,0.0872f,-0.9962f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7071f,0.7071f,0f,0.3562f,0.7071f,0.7071f,0f,1.3543f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7071f,-0.7071f,0f,-0.3688f,-0.7071f,0.7071f,0f,1.3543f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,0.2164f,0.9763f,1.4099f,0f,0.9763f,-0.2164f,0.4414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0563f,0f,0.766f,0.6428f,0.6305f,0f,0.6428f,-0.766f,-0.0494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3187f,0f,0.514f,0f,0.3304f,1.8194f,1.4904f,1.5397f,-0.3938f,1.5266f,-1.7762f,-0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3187f,0f,-0.514f,0f,-0.3304f,1.8194f,1.4904f,1.4277f,0.3938f,1.5266f,-1.7762f,-0.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}