# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0021f,0.9216f,0f,0.0021f,-1f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9964f,0.0851f,0.9216f,0f,0.0851f,-0.9964f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7085f,0.7057f,0f,0.3562f,0.7057f,0.7085f,0.0001f,1.4004f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7085f,-0.7057f,0f,-0.3688f,-0.7057f,0.7085f,0.0001f,1.4004f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,0.2174f,0.9761f,1.456f,0f,0.9761f,-0.2174f,0.4414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0563f,0f,0.766f,0.6428f,0.6766f,0f,0.6428f,-0.766f,-0.0494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3641f,0f,0.2268f,0f,0.1458f,1.8194f,1.5196f,1.5859f,-0.1737f,1.5266f,-1.811f,-0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3641f,0f,-0.2268f,0f,-0.1458f,1.8194f,1.5196f,1.4739f,0.1737f,1.5266f,-1.811f,-0.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}