# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-1f,0f,0f,-0.125f,0f,0.9962f,0.0865f,0.9874f,0f,0.0865f,-0.9962f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0006f,0.9874f,0f,0.0006f,-1f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7656f,0.6433f,0f,0.3562f,0.6433f,0.7656f,0f,1.4661f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7656f,-0.6433f,0f,-0.3688f,-0.6433f,0.7656f,0f,1.4661f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,0.2585f,0.966f,1.5217f,0f,0.966f,-0.2585f,0.4414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0563f,0f,0.766f,0.6428f,0.7424f,0f,0.6428f,-0.766f,-0.0494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3344f,0f,0.4373f,0f,0.2811f,1.8194f,1.5005f,1.6516f,-0.335f,1.5266f,-1.7883f,-0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3344f,0f,-0.4373f,0f,-0.2811f,1.8194f,1.5005f,1.5396f,0.335f,1.5266f,-1.7883f,-0.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}