# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0006f,0.9915f,0f,0.0006f,-1f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9962f,0.0865f,0.9915f,0f,0.0865f,-0.9962f,-0.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7075f,0.7067f,0f,0.3562f,0.7067f,0.7075f,0f,1.4702f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7075f,-0.7067f,0f,-0.3688f,-0.7067f,0.7075f,0f,1.4702f,0f,0f,-1f,0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,0.2167f,0.9762f,1.5258f,0f,0.9762f,-0.2167f,0.4414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0563f,0f,0.766f,0.6428f,0.7465f,0f,0.6428f,-0.766f,-0.0494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3344f,0f,0.4373f,0f,0.2811f,1.8194f,1.5005f,1.6557f,-0.335f,1.5266f,-1.7883f,-0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3344f,0f,-0.4373f,0f,-0.2811f,1.8194f,1.5005f,1.5437f,0.335f,1.5266f,-1.7883f,-0.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}