# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (stellarity:util/animated_java/pixie)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'No Variants',underlined:true},'\n\n ','This Blueprint has no variants to switch between.','\n']
function stellarity:util/animated_java/pixie/remove/this/without_on_remove_function
scoreboard players set #success aj.i 0