# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute if function stellarity:util/animated_java/eol/variants/$(variant)/apply run return 1
return fail