# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:yellow_pixie rig_hash set value '379548520414704f61dda363263eaf599f96402bbfbbb1ba2ac607faaf5d4c8a'
scoreboard objectives add aj.flying_pixie.frame dummy
scoreboard objectives add aj.idle_pixie.frame dummy