# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tellraw @a [{color:'red',text:''},{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:yellow_pixie)'},'\n → ᴇʀʀᴏʀ: ',{color:'red',underlined:true,text:'No Variants'},'\n\n This Blueprint has no variants to switch between.\n']
function animated_java:yellow_pixie/remove/this/without_on_remove_function
scoreboard players set #success aj.i 0