# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(bone) run function stellarity:util/animated_java/pixie/variants/magenta_pixie/zzz/apply_to_node_bone
$execute as $(bone1) run function stellarity:util/animated_java/pixie/variants/magenta_pixie/zzz/apply_to_node_bone1
$execute as $(bone2) run function stellarity:util/animated_java/pixie/variants/magenta_pixie/zzz/apply_to_node_bone2