# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "stellarity:util/animated_java/eol"
data modify storage animated_java:temp entry.data.rig_hash set value "95ead5b64a2d923683ca03504e6792a874f6e6efa420a7f8cf055c9633009ff7"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone7] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone8] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone3] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone4] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone10] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone9] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone1] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.eol.node.bone] run function stellarity:util/animated_java/eol/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function stellarity:util/animated_java/eol/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function stellarity:util/animated_java/eol/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function stellarity:util/animated_java/eol/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new