# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:yellow_pixie/animations/idle_pixie/zzz/apply_frame {frame: 2}
scoreboard players add @s aj.idle_pixie.frame 1