# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.yellow_pixie.root] run return 0
execute if entity @s[tag=aj.yellow_pixie.animation.flying_pixie.playing] run function animated_java:yellow_pixie/animations/flying_pixie/zzz/on_tick
execute if entity @s[tag=aj.yellow_pixie.animation.idle_pixie.playing] run function animated_java:yellow_pixie/animations/idle_pixie/zzz/on_tick
execute on passengers run rotate @s ~ ~