# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(bone7) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone7
$execute as $(bone8) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone8
$execute as $(bone3) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone3
$execute as $(bone4) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone4
$execute as $(bone10) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone10
$execute as $(bone9) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone9
$execute as $(bone1) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone1
$execute as $(bone) run function stellarity:util/animated_java/eol/variants/daylight_hurt/zzz/apply_to_node_bone