# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=stellarity.util.animated_java.pixie.animation.idle_pixie.playing] run function stellarity:util/animated_java/pixie/animations/idle_pixie/zzz/on_tick
execute if entity @s[tag=stellarity.util.animated_java.pixie.animation.flying_pixie.playing] run function stellarity:util/animated_java/pixie/animations/flying_pixie/zzz/on_tick
execute on passengers run rotate @s ~ ~