# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp uuids append from storage animated_java:gu out
execute on passengers run function animated_java:global/util/zzz/0