# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute if data storage animated_java:$(export_namespace) {rig_hash:'$(rig_hash)'} run return 0
return 1