# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp uuids
execute on passengers run function animated_java:global/util/zzz/0