# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function stellarity:util/animated_java/eol/animations/pause_all
tag @s add stellarity.util.animated_java.eol.animation.eol_dash.playing
scoreboard players set @s aj.eol_dash.frame 0
tag @s add aj.transforms_only
execute at @s run function stellarity:util/animated_java/eol/animations/eol_dash/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only