# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) { transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,0.3125f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone1) { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.375f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone2) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,0.375f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f], start_interpolation: 0 }