# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
advancement revoke @s only animated_java:global/interactions/interaction/trigger
tag @s add aj.interacting_player
execute as @e[type=interaction, tag=aj.global.interaction, distance=..8] if data entity @s interaction run function animated_java:global/interactions/interaction/check
tag @s remove aj.interacting_player