# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #success aj.i 0
execute if data storage animated_java:temp {args:{animation:''}} run return run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/if_empty
execute store result storage animated_java:temp args.frame int 1 store result score #frame aj.i run data get storage animated_java:temp args.frame
execute if score #frame aj.i matches ..-1 run return run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/no_negative
execute store success score #success aj.i run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/try_set_frame with storage animated_java:temp args
execute unless score #success aj.i matches 1 run return run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/invalid_animation
execute if data storage animated_java:temp {args:{start_animation: true}} run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/start_animation with storage animated_java:temp args
scoreboard players set #success aj.i 1