# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(bone7)
$kill $(bone8)
$kill $(bone3)
$kill $(bone4)
$kill $(bone10)
$kill $(bone9)
$kill $(bone1)
$kill $(bone)