# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function stellarity:util/animated_java/pixie/animations/flying_pixie/zzz/frames/last_frame_effects with storage animated_java:temp entry.data.uuids_by_name
scoreboard players add @s aj.flying_pixie.frame 1