# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.$(name)
function stellarity:util/animated_java/eol/zzz/as_node/execute_as_uuid with storage animated_java:temp args