# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "stellarity:util/animated_java/pixie"
data modify storage animated_java:temp entry.data.rig_hash set value "1fc553b74340010324e2c0c619ba8ce4fc37721ddeeadfcf9e0720d40b61f9bf"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=stellarity.util.animated_java.pixie.node.bone] run function stellarity:util/animated_java/pixie/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.pixie.node.bone1] run function stellarity:util/animated_java/pixie/zzz/summon/as_node/bone1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=stellarity.util.animated_java.pixie.node.bone2] run function stellarity:util/animated_java/pixie/zzz/summon/as_node/bone2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone2 set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function stellarity:util/animated_java/pixie/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function stellarity:util/animated_java/pixie/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function stellarity:util/animated_java/pixie/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new