# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:yellow_pixie/animations/flying_pixie/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.flying_pixie.frame 1