# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1247f,0.5599f,-0.125f,0.1241f,0.9144f,0.3853f,0.7509f,-0.56f,0.3851f,-0.7336f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9541f,0.2995f,0.7509f,0f,0.2995f,-0.9541f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-1f,0.0016f,0f,0.3562f,0.0016f,1f,0f,1.3759f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-1f,-0.0016f,0f,-0.3688f,-0.0016f,1f,0f,1.3759f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5009f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.5884f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3457f,0f,-0.3716f,0f,0f,2.375f,0f,1.2509f,0.3716f,0f,-2.3457f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3457f,0f,0.3716f,0f,0f,2.375f,0f,1.1572f,-0.3716f,0f,-2.3457f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}