# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1762f,0.5459f,-0.125f,0.1241f,0.8747f,0.4686f,0.8398f,-0.56f,0.4516f,-0.6946f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9838f,0.1791f,0.8398f,0f,0.1791f,-0.9838f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9877f,0.1561f,0f,0.3562f,0.1561f,0.9877f,0f,1.4648f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9877f,-0.1561f,0f,-0.3688f,-0.1561f,0.9877f,0f,1.4648f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5898f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6773f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5747f,0f,-2.3044f,0f,0f,2.375f,0f,1.3398f,2.3044f,0f,-0.5747f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5747f,0f,2.3044f,0f,0f,2.375f,0f,1.246f,-2.3044f,0f,-0.5747f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}