# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1809f,0.5443f,-0.125f,0.1241f,0.8706f,0.4761f,0.848f,-0.56f,0.4576f,-0.6907f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9858f,0.1678f,0.848f,0f,0.1678f,-0.9858f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9854f,0.1702f,0f,0.3562f,0.1702f,0.9854f,0f,1.473f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9854f,-0.1702f,0f,-0.3688f,-0.1702f,0.9854f,0f,1.473f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.598f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6855f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1.751f,0f,-1.6045f,0f,0f,2.375f,0f,1.348f,1.6045f,0f,-1.751f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-1.751f,0f,1.6045f,0f,0f,2.375f,0f,1.2542f,-1.6045f,0f,-1.751f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}