# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1851f,0.5429f,-0.125f,0.1241f,0.8668f,0.4829f,0.8555f,-0.56f,0.463f,-0.6871f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9875f,0.1575f,0.8555f,0f,0.1575f,-0.9875f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9831f,0.183f,0f,0.3562f,0.183f,0.9831f,0f,1.4805f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9831f,-0.183f,0f,-0.3688f,-0.183f,0.9831f,0f,1.4805f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6055f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.693f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3457f,0f,-0.3716f,0f,0f,2.375f,0f,1.3555f,0.3716f,0f,-2.3457f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3457f,0f,0.3716f,0f,0f,2.375f,0f,1.2617f,-0.3716f,0f,-2.3457f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}