# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1262f,0.5595f,-0.125f,0.1241f,0.9134f,0.3878f,0.7535f,-0.56f,0.3871f,-0.7325f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9552f,0.296f,0.7535f,0f,0.296f,-0.9552f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-1f,0.0061f,0f,0.3562f,0.0061f,1f,0f,1.3785f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-1f,-0.0061f,0f,-0.3688f,-0.0061f,1f,0f,1.3785f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5035f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.591f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1.751f,0f,-1.6045f,0f,0f,2.375f,0f,1.2535f,1.6045f,0f,-1.751f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-1.751f,0f,1.6045f,0f,0f,2.375f,0f,1.1598f,-1.6045f,0f,-1.751f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}