# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1962f,0.539f,-0.125f,0.1241f,0.8568f,0.5005f,0.875f,-0.56f,0.4769f,-0.6775f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9914f,0.1305f,0.875f,0f,0.1305f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9763f,0.2164f,0f,0.3562f,0.2164f,0.9763f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9763f,-0.2164f,0f,-0.3688f,-0.2164f,0.9763f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.7125f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.207f,0f,-2.366f,0f,0f,2.375f,0f,1.375f,2.366f,0f,-0.207f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.207f,0f,2.366f,0f,0f,2.375f,0f,1.2813f,-2.366f,0f,-0.207f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}