# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1942f,0.5397f,-0.125f,0.1241f,0.8586f,0.4974f,0.8715f,-0.56f,0.4744f,-0.6792f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9908f,0.1354f,0.8715f,0f,0.1354f,-0.9908f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9776f,0.2105f,0f,0.3562f,0.2105f,0.9776f,0f,1.4965f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9776f,-0.2105f,0f,-0.3688f,-0.2105f,0.9776f,0f,1.4965f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6215f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.709f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1.751f,0f,-1.6045f,0f,0f,2.375f,0f,1.3715f,1.6045f,0f,-1.751f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-1.751f,0f,1.6045f,0f,0f,2.375f,0f,1.2778f,-1.6045f,0f,-1.751f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}