# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1888f,0.5416f,-0.125f,0.1241f,0.8635f,0.4888f,0.862f,-0.56f,0.4676f,-0.6839f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9889f,0.1485f,0.862f,0f,0.1485f,-0.9889f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.981f,0.1942f,0f,0.3562f,0.1942f,0.981f,0f,1.487f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.981f,-0.1942f,0f,-0.3688f,-0.1942f,0.981f,0f,1.487f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.612f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6995f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.362f,0f,0f,-2.375f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.2683f,0f,0f,-2.375f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}