# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1711f,0.5475f,-0.125f,0.1241f,0.8789f,0.4605f,0.831f,-0.56f,0.4452f,-0.6987f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9816f,0.1912f,0.831f,0f,0.1912f,-0.9816f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.99f,0.1409f,0f,0.3562f,0.1409f,0.99f,0f,1.456f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.99f,-0.1409f,0f,-0.3688f,-0.1409f,0.99f,0f,1.456f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.581f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6685f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.207f,0f,-2.366f,0f,0f,2.375f,0f,1.331f,2.366f,0f,-0.207f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.207f,0f,2.366f,0f,0f,2.375f,0f,1.2373f,-2.366f,0f,-0.207f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}