# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1659f,0.5491f,-0.125f,0.1241f,0.8833f,0.4521f,0.8218f,-0.56f,0.4385f,-0.703f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.979f,0.2037f,0.8218f,0f,0.2037f,-0.979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9921f,0.1251f,0f,0.3562f,0.1251f,0.9921f,0f,1.4468f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9921f,-0.1251f,0f,-0.3688f,-0.1251f,0.9921f,0f,1.4468f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5718f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6593f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5747f,0f,-2.3044f,0f,0f,2.375f,0f,1.3218f,2.3044f,0f,-0.5747f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5747f,0f,2.3044f,0f,0f,2.375f,0f,1.2281f,-2.3044f,0f,-0.5747f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}