# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1447f,0.555f,-0.125f,0.1241f,0.9f,0.4179f,0.7852f,-0.56f,0.4112f,-0.7193f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9673f,0.2535f,0.7852f,0f,0.2535f,-0.9673f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9981f,0.0614f,0f,0.3562f,0.0614f,0.9981f,0f,1.4102f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9981f,-0.0614f,0f,-0.3688f,-0.0614f,0.9981f,0f,1.4102f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5352f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6227f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3457f,0f,-0.3716f,0f,0f,2.375f,0f,1.2852f,0.3716f,0f,-2.3457f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3457f,0f,0.3716f,0f,0f,2.375f,0f,1.1915f,-0.3716f,0f,-2.3457f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}