# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1399f,0.5562f,-0.125f,0.1241f,0.9035f,0.4101f,0.777f,-0.56f,0.405f,-0.7228f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9644f,0.2645f,0.777f,0f,0.2645f,-0.9644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9989f,0.0471f,0f,0.3562f,0.0471f,0.9989f,0f,1.402f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9989f,-0.0471f,0f,-0.3688f,-0.0471f,0.9989f,0f,1.402f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.527f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6145f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1.751f,0f,-1.6045f,0f,0f,2.375f,0f,1.277f,1.6045f,0f,-1.751f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-1.751f,0f,1.6045f,0f,0f,2.375f,0f,1.1833f,-1.6045f,0f,-1.751f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}