# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1318f,0.5582f,-0.125f,0.1241f,0.9095f,0.3968f,0.763f,-0.56f,0.3944f,-0.7286f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.959f,0.2833f,0.763f,0f,0.2833f,-0.959f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9997f,0.0227f,0f,0.3562f,0.0227f,0.9997f,0f,1.388f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9997f,-0.0227f,0f,-0.3688f,-0.0227f,0.9997f,0f,1.388f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.513f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6005f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.207f,0f,-2.366f,0f,0f,2.375f,0f,1.263f,2.366f,0f,-0.207f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.207f,0f,2.366f,0f,0f,2.375f,0f,1.1692f,-2.366f,0f,-0.207f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}