# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1286f,0.559f,-0.125f,0.1241f,0.9117f,0.3917f,0.7576f,-0.56f,0.3902f,-0.7309f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9569f,0.2906f,0.7576f,0f,0.2906f,-0.9569f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9999f,0.0133f,0f,0.3562f,0.0133f,0.9999f,0f,1.3826f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9999f,-0.0133f,0f,-0.3688f,-0.0133f,0.9999f,0f,1.3826f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5076f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.5951f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5747f,0f,-2.3044f,0f,0f,2.375f,0f,1.2576f,2.3044f,0f,-0.5747f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5747f,0f,2.3044f,0f,0f,2.375f,0f,1.1638f,-2.3044f,0f,-0.5747f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}