# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1356f,0.5573f,-0.125f,0.1241f,0.9067f,0.403f,0.7695f,-0.56f,0.3993f,-0.7259f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9616f,0.2746f,0.7695f,0f,0.2746f,-0.9616f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9994f,0.0341f,0f,0.3562f,0.0341f,0.9994f,0f,1.3945f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9994f,-0.0341f,0f,-0.3688f,-0.0341f,0.9994f,0f,1.3945f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5195f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.607f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5747f,0f,-2.3044f,0f,0f,2.375f,0f,1.2695f,2.3044f,0f,-0.5747f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5747f,0f,2.3044f,0f,0f,2.375f,0f,1.1758f,-2.3044f,0f,-0.5747f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}