# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1498f,0.5537f,-0.125f,0.1241f,0.8961f,0.4261f,0.794f,-0.56f,0.4178f,-0.7154f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9704f,0.2416f,0.794f,0f,0.2416f,-0.9704f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9971f,0.0767f,0f,0.3562f,0.0767f,0.9971f,0f,1.419f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9971f,-0.0767f,0f,-0.3688f,-0.0767f,0.9971f,0f,1.419f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.544f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6315f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.294f,0f,0f,-2.375f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.2003f,0f,0f,-2.375f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}