# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) {transformation: [-0.8192f,-0.1551f,0.5522f,-0.125f,0.1241f,0.892f,0.4347f,0.8032f,-0.56f,0.4246f,-0.7114f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone8) {transformation: [-1f,0f,0f,0.125f,0f,0.9734f,0.2292f,0.8032f,0f,0.2292f,-0.9734f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9957f,0.0926f,0f,0.3562f,0.0926f,0.9957f,0f,1.4282f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9957f,-0.0926f,0f,-0.3688f,-0.0926f,0.9957f,0f,1.4282f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5532f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone9) {transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.6407f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-2.3457f,0f,-0.3716f,0f,0f,2.375f,0f,1.3032f,0.3716f,0f,-2.3457f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-2.3457f,0f,0.3716f,0f,0f,2.375f,0f,1.2094f,-0.3716f,0f,-2.3457f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}