# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage stellarity:util/animated_java/eol rig_hash set value '95ead5b64a2d923683ca03504e6792a874f6e6efa420a7f8cf055c9633009ff7'
scoreboard objectives add aj.eol_flying.frame dummy
scoreboard objectives add aj.eol_dash.frame dummy
scoreboard objectives add aj.eol_death.frame dummy
scoreboard objectives add aj.eol_healing.frame dummy