# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.eol_flying.frame
scoreboard objectives remove aj.eol_dash.frame
scoreboard objectives remove aj.eol_death.frame
scoreboard objectives remove aj.eol_healing.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (stellarity:util/animated_java/eol)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'stellarity:util/animated_java/eol',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']