# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score #gametime aj.i run time query gametime
execute store result score #timestamp aj.i run data get entity @s attack.timestamp
scoreboard players set #check aj.i 0
execute if score #timestamp aj.i = #gametime aj.i if data entity @s data.animated_java.on_attack_function store success score #check aj.i on attacker if entity @s[tag=aj.interacting_player]
execute if score #check aj.i matches 1 run function animated_java:global/interactions/attack/do