# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #check aj.i 0
function animated_java:global/interactions/attack/execute with entity @s data.animated_java
execute if score #check aj.i matches 0 run tellraw @a [ {text: '', color: red}, {text:'ɪɴᴛᴇʀᴀᴄᴛɪᴏɴꜱ', color:'light_purple'}, {text:'\n(.mcb)', color:'dark_gray'}, '\n→ ᴇʀʀᴏʀ:\n\sFailed to handle left click interaction from ', {selector: '@p[tag=aj.interacting_player]', color: gold}, ':\n\s\sInvalid command: ', {nbt: 'data.animated_java.on_attack_function', entity: '@s', color: aqua}, '\n\s\sfrom ', {text: 'data.animated_java.on_attack_function ', color: yellow}, ]
data remove entity @s attack