# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
advancement revoke @s only animated_java:global/interactions/attack/trigger
tag @s add aj.interacting_player
execute as @e[type=interaction, tag=aj.global.interaction, distance=..8] if data entity @s attack run function animated_java:global/interactions/attack/check
tag @s remove aj.interacting_player