# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function stellarity:util/animated_java/pixie/variants/red_pixie/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
return 1