# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=stellarity.util.animated_java.eol.animation.eol_flying.playing] run function stellarity:util/animated_java/eol/animations/eol_flying/zzz/on_tick
execute if entity @s[tag=stellarity.util.animated_java.eol.animation.eol_dash.playing] run function stellarity:util/animated_java/eol/animations/eol_dash/zzz/on_tick
execute if entity @s[tag=stellarity.util.animated_java.eol.animation.eol_death.playing] run function stellarity:util/animated_java/eol/animations/eol_death/zzz/on_tick
execute if entity @s[tag=stellarity.util.animated_java.eol.animation.eol_healing.playing] run function stellarity:util/animated_java/eol/animations/eol_healing/zzz/on_tick
execute on passengers run rotate @s ~ ~