# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove stellarity.util.animated_java.pixie.animation.idle_pixie.playing
tag @s remove stellarity.util.animated_java.pixie.animation.flying_pixie.playing