# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function stellarity:util/animated_java/eol/animations/eol_death/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1