# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:yellow_pixie/animations/pause_all
tag @s add aj.yellow_pixie.animation.idle_pixie.playing
scoreboard players set @s aj.idle_pixie.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:yellow_pixie/animations/idle_pixie/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only