# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage animated_java:temp args.id int 1 run scoreboard players get #aj.data_manager.index aj.i
function animated_java:global/data_manager/zzz/0 with storage animated_java:temp args
scoreboard players add #aj.data_manager.index aj.i 1
execute if score #aj.data_manager.index aj.i > aj.last_id aj.id run scoreboard players set #aj.data_manager.index aj.i 0