# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp entry
$data modify storage animated_java:temp entry set from storage animated_java:data "$(id)"