# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[type=!player] run function animated_java:global/remove/entity_stack
kill @s