# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data remove storage animated_java:temp args
data remove storage animated_java:temp uuids
data modify storage animated_java:temp uuids set from entity @s data.uuids
execute store result score #aj.length aj.i run data get storage animated_java:temp uuids
execute if score #aj.length aj.i matches 1.. run function animated_java:global/remove/loop_over_uuids
function animated_java:global/remove/entity_stack