# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone7) { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone8) { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone3) { transformation: [-1f,0f,0f,0.3562f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone4) { transformation: [-1f,0f,0f,-0.3688f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone10) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone9) { transformation: [-1f,0f,0f,0.0562f,0f,1f,0f,0.5875f,0f,0f,-1f,0.1875f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone1) { transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.25f,0f,0f,-2.375f,-0.4375f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone) { transformation: [-2.375f,0f,0f,0f,0f,2.375f,0f,1.1563f,0f,0f,-2.375f,-0.375f,0f,0f,0f,1f], start_interpolation: 0 }